name: extended_svg_picture
description: ğŸš€ Load SVG with caching via ExtendedImage. Supports dynamic color, retries, and full customization.
version: 0.0.1
homepage: https://github.com/tianguanghui/extended_svg_picture
repository: https://github.com/tianguanghui/extended_svg_picture

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  extended_image: ^7.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0